services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/app:cached
      # node＿modulesがroot権限になってしまう場合は
      # 一度コメントアウトして、mkdir node_modules してから
      # 有効にする
      - node_modules:/app/node_modules
    command: sleep infinity
    network_mode: service:db

  db:
    image: postgres:16-alpine
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

volumes:
  postgres-data:
  node_modules:
